# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildCOnfiguration: 'Release'


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(solution)'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '$(solution)'
    feedsToUse: 'select'
##task: DotNetCoreCLI@2
##  displayName: Test
##  inputs:
##   command: 'test'
##    projects: '$(solution)'
##    feedsToUse: 'select'

